Компоненты
js-tasks-ru/vue-20230905_merkulov-vladimir-67 pull request #3
Opened 2023-10-11 14:18 UTC by VladimirMer-1967

Решение задач по теме "Компоненты"

2023-10-11 14:19 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-11 17:49 UTC, ShGKme requested changes
Хотя все компоненты работают и проходят тестирование, есть большое количество небольших замечаний по стилю и использованию отдельных возможностей Vue.

Лучше их сразу поправить, чтобы закрепить, и они не повторялись в будущем.

2023-10-11 17:49 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    }
`required: true` и `default` обычно не нужны одновременно. `required: true` означает, что пропс обязательно должен быть передан. А `default` нужен, чтобы определять значение не переданного пропса (который передавать обязательно).

2023-10-11 17:49 UTC, ShGKme commented on 02-components/03-MeetupCover/components/MeetupCover.js
> +    },
Такой способ сложения строк работает, но выглядит очень непривычно и редко применяется в JS.

Есть обычное сложение строк оператором конкатенации:
```js
'--bg-url: url(' + `${t}` + ')'
```

И есть шаблонные строки
```js
`--bg-url: url('${t}')`
```

2023-10-11 17:49 UTC, ShGKme commented on 02-components/03-MeetupCover/components/MeetupCover.js
> +    },
При этом такая шаблонная строка, как `${t}` - не имеет смысла, так как она целиком состоит из переменной и не отличается от просто использования переменной `t`.

2023-10-11 17:49 UTC, ShGKme commented on 02-components/03-MeetupCover/components/MeetupCover.js
> +   <div class="meetup-cover" v-if="image != null" v-bind:style="getImageUrl(\`\${image}\`)" >
Обычно используют сокращённую запись директив `:style=""`, без `v-bind`

2023-10-11 17:49 UTC, ShGKme commented on 02-components/03-MeetupCover/components/MeetupCover.js
>      </div>`,
Когда по условию меняется лишь значение одного атрибута, лучше в шаблоне определять условием именно это значение или выносить это в вычисляемое свойство.

С `v-if` получается копирование целиком вообще всего узла со всем его содержимым, это дублирование всего кода узла, а в этом случае даже всего компонента.

Чтобы не устанавливать значение атрибута, можно присвоить любое falsy значение: `''`, `false`, `null`, `undefiend`

2023-10-11 17:49 UTC, ShGKme commented on 02-components/04-MeetupInfo/components/MeetupInfo.js
> +        <time v-bind:datetime ="formatDateISO(this.date)">{{ formatDate(this.date) }}</time>
`this` в шаблоне не используют, он уже работает в области видимости свойств экземпляра компонента

2023-10-11 17:49 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgenda.js
> +    agenda: [],
Пустой массив `[]` - это некорректное описание параметра.

Параметр описывается либо только типом-конструктором (`Array`, `String`), либо объектом описания со свойствами:

```js
{
  type: ...
  required: ...
  validator: () => {}
  default: 
}
```

2023-10-11 17:49 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgenda.js
> +      </div>
Для использования `v-for` на узле (в том числе на компоненте), его не нужно оборачивать в ещё один HTML элемент. `div` тут лишний

2023-10-11 17:49 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +    },
Лучше всегда описывать параметры как можно подробнее, хотя бы описывая их тип и обязательность.

2023-10-11 17:49 UTC, ShGKme commented on 02-components/06-MeetupView/components/MeetupView.js
> +            <div v-else><MeetupAgenda :agenda="this.meetup.agenda" /></div>
Аналогично циклу, для использования `v-if/v-else` на узле (в том числе на компоненте), его не нужно оборачивать в ещё один див.

2023-10-11 17:49 UTC, ShGKme commented on 02-components/06-MeetupView/components/MeetupView.js
> +            </div>
Проверка `meetup.agenda == []` никогда не будет истинной. Массивы в JS сравниваются по ссылке. Здесь сравнивается значение в свойстве `agenda` с новым созданным прямо тут массивом. Новый массив гарантированно не будет той ссылкой, что лежит в данных

2023-10-11 17:49 UTC, ShGKme commented on 02-components/06-MeetupView/components/MeetupView.js
> +            </div>
Программа — это массив. Она не может быть пустой строкой.

Пустая программа - это пустой массив. Пустоту массива можно проверить через свойство `length`

2023-10-11 17:49 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +    };
Конструктор `Object` - точно не валидное начальное значение для `meetup` и `error`. Там не хранится тип/класс/конструктор, там хранятся данные. Начальным значением лучше указать `null`, как явное указание на отсутствие данных.

В `data` описываются именно сами данные, а не их типы, как в `props`, где описывается интерфейс компонента для данных, которые получаются от родителя.

2023-10-11 17:49 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +       });
Лучше не оставлять лог в итоговом решении, чтобы не засорять отчёт тестирования.

2023-10-13 15:55 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-13 19:12 UTC, VladimirMer-1967 commented
исправлены замечания

2023-10-15 16:41 UTC, ShGKme requested changes
В `02-components/05-MeetupAgenda` некорректное описание входных параметров.

Остальные задачи приняты, но обратите внимание на комментарии

2023-10-15 16:41 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgenda.js
> +  },
Здесь получилось описание, в котором описывается два параметра:
- `agenda` типа `Array`
- `required`

2023-10-15 16:41 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgenda.js
> +  },
В короткой форме параметр описывается только типом (`agenda: Array`).
В полной - объектом с описанием:
```js
agenda: {
  type: Array,
  required: true,
}
```

2023-10-15 16:41 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgenda.js
>        </li>
Не обратил внимание в прошлый раз. Цикл должен быть на элементе списка `li`.

Иначе здесь список из одного элемента в HTML, внутри которого выводятся сразу ВСЕ пункты программы

2023-10-15 16:41 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        <h3 class="agenda-item__title" v-else > {{ getTitle(agendaItem.type) }}</h3>
Когда по условию меняется лишь содержимое узла, лучше в шаблоне определять условием именно содержимое (тернарным оператором) или выносить это в вычисляемое свойство.

С `v-if` получается копирование целиком узла, это дублирование всего кода узла.

2023-10-15 16:41 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        },
Эти методы только вычисляют значение от своих параметров, при этом в их параметр никогда не передают ничего, кроме конкретного значения - свойства их пропса.

Лучше такие методы описать как вычисляемые свойства.

Тогда их не потребуется вызывать внутри шаблона, вычисляя контент при каждом рендеринге, а компонент будет проще отлаживать (вычисляемые свойства видно в девтулсах).

2023-10-15 16:41 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        },
Аналогично `getImageUrl` в предыдущей задаче

2023-10-15 16:41 UTC, ShGKme commented on 02-components/03-MeetupCover/components/MeetupCover.js
> +    },
Это не относится к `Vue`, но не нужно всегда приводить значение к строке, особенно если с ним не нужно работать всегда как со строкой или там итак лежит всегда строка.

И в этой задаче и в последующих запись вида `${t}` можно заменить на просто `t`.

Тогда и проверку на наличие значение можно будет явно сравнивать с `undefined` (непосредственно со значением `undefined`, а не со строкой `'undefined'`), либо просто использовать простую проверку `if (t) {`

2023-10-16 18:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-16 18:30 UTC, VladimirMer-1967 commented
Исправление ошибок

2023-10-16 18:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-16 21:24 UTC, ShGKme reviewed
Исправления приняты

2023-10-25 06:24 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-25 18:34 UTC, ShGKme requested changes

2023-10-25 18:34 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +    },
Когда изображения нет, здесь получится некорректное значение в `CSS`: `url(undefined)` вместо фона по умолчанию `var(--default-cover)`

2023-10-25 19:07 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-25 19:09 UTC, VladimirMer-1967 commented
исправлена фунцкия

2023-10-25 19:14 UTC, ShGKme approved these changes
Все задачи приняты

2023-10-25 19:16 UTC, merged